spring:
#  静态资源处理
  resources:
#    启动默认静态资源处理
    add-mappings: true
    cache:
      cachecontrol:
#        缓存相应时间
        max-age: 3600
    chain:
#      资源链启动缓存 默认启动
      cache: true
#      启动资源链 默认禁用
      enabled: true
#      启动压缩资源（gzip brotli）解析， 默认禁用
      compressed: true
#      启用h5应用缓存 默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  #  关于thymeleaf配置
  thymeleaf:
    cache: false
  #    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill-final?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      #      最小空闲连接数
      minimum-idle: 5
      #      空闲连接存活时间 默认10分钟
      idle-timeout: 18000
      #      最大连接数
      maximum-pool-size: 10
      #      从连接池返回的连接自动提交
      auto-commit: true
      #      连接最大存活时间 0代表永久 默认1800000
      max-lifetime: 180000
      #     连接超时时间
      connection-timeout: 30000
      #      测试连接书否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 192.168.126.128
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
#        最大活跃数
        max-active: 8
#        最长等待时间
        max-wait: 10000ms
#        最大空闲连接
        max-idle: 200
#        最小控线连接
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:/com.cheny.springbootseckill.mapper/*Mapper.xml
  type-aliases-package: com.cheny.springbootseckill.pojo
logging:
  level:
    com.cheny.springbootseckill.mapper: debug


